import { OrchestratorResponse, VerdictItem } from '../types/sentinel';

export class ExportService {
  static toJSON(data: OrchestratorResponse): string {
    return JSON.stringify(data, null, 2);
  }

  static toCSV(verdicts: VerdictItem[]): string {
    if (!verdicts || verdicts.length === 0) return 'account_id,risk_score,flagged,ring_id,explanation\n';

    const headers = ['account_id', 'risk_score', 'flagged', 'ring_id', 'explanation'];
    const rows = verdicts.map((v) => [
      `"${v.account_id}"`,
      v.risk_score.toFixed(4),
      v.flagged ? 'true' : 'false',
      `"${v.ring_id || ''}"`,
      `"${(v.explanation || '').replace(/"/g, '""')}"`,
    ]);

    return [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
  }

  static toMarkdown(data: OrchestratorResponse): string {
    const verdicts = data.verdict || [];
    const flagged = verdicts.filter((v) => v.flagged);
    const rings = Array.from(new Set(verdicts.map((v) => v.ring_id).filter(Boolean)));

    return `# Sentinel Ring — Fraud Analysis Report

**Date:** ${data.created_at || new Date().toISOString()}
**Dataset:** ${data.dataset_name || 'Synthetic Scenario'}
**Total Transactions Analyzed:** ${data.total_transactions || verdicts.length}
**Total Accounts Evaluated:** ${verdicts.length}
**Flagged Accounts:** ${flagged.length}
**Louvain Ring Clusters Detected:** ${rings.length}

---

## Executive Summary Verdicts

| Account ID | Risk Score | Flag Status | Ring ID | Evidence Explanation |
|------------|------------|-------------|---------|-----------------------|
${verdicts
  .map(
    (v) =>
      `| \`${v.account_id}\` | ${v.risk_score.toFixed(4)} | ${
        v.flagged ? '🚨 FLAGGED' : '✅ SAFE'
      } | \`${v.ring_id || '—'}\` | ${v.explanation || 'Normal activity.'} |`
  )
  .join('\n')}

---

## Governance Notice
*This report was generated by Sentinel Ring. System is defense-only. Zero auto-blocking.*
`;
  }
}
